### ISSUE TITLE
Les numéros 0 ne sont pas exportés dans le CSV

### ISSUE THREAD

**Issue by tmerlier** [etalab/api-bal#242]
Si des numéros 0 se trouve dans la Base Adresse Locale et qu'on export au format CSV, les numéros 0 ne sont plus présents.

**Comment by jdesboeufs** [comment]
Toujours présent ? @GllmR tu peux jeter un oeil ?

**Comment by GllmR** [comment]
Les numéros zéro sont bien exportés dans le CSV, mais ils arrivent à la fin de la liste des numéros, juste avant les toponymes.

![Capture d’écran 2021-09-07 à 10 36 13](https://user-images.githubusercontent.com/56537238/132313514-affd78bc-b3a8-4bb1-8542-b94e50a22ea8.png)
